insert into estado (codigo_ibge, sigla, nome) values (11,'RO', 'Rondonia');
insert into estado (codigo_ibge, sigla, nome) values (12,'AC', 'Acre');
insert into estado (codigo_ibge, sigla, nome) values (13,'AM', 'Amazonas');
insert into estado (codigo_ibge, sigla, nome) values (14,'RR', 'Roraima');
insert into estado (codigo_ibge, sigla, nome) values (15,'PA', 'Para');
insert into estado (codigo_ibge, sigla, nome) values (16,'AP', 'Amapa');
insert into estado (codigo_ibge, sigla, nome) values (17,'TO', 'Tocantins');
insert into estado (codigo_ibge, sigla, nome) values (21,'MA', 'Maranhao');
insert into estado (codigo_ibge, sigla, nome) values (22,'PI', 'Piaui');
insert into estado (codigo_ibge, sigla, nome) values (23,'CE', 'Ceara');
insert into estado (codigo_ibge, sigla, nome) values (24,'RN', 'Rio Grande do Norte');
insert into estado (codigo_ibge, sigla, nome) values (25,'PB', 'Paraiba');
insert into estado (codigo_ibge, sigla, nome) values (26,'PE', 'Pernambuco');
insert into estado (codigo_ibge, sigla, nome) values (27,'AL', 'Alagoas');
insert into estado (codigo_ibge, sigla, nome) values (28,'SE', 'Sergipe');
insert into estado (codigo_ibge, sigla, nome) values (29,'BA', 'Bahia');
insert into estado (codigo_ibge, sigla, nome) values (31,'MG', 'Minas Gerais');
insert into estado (codigo_ibge, sigla, nome) values (32,'ES', 'Espirito Santo');
insert into estado (codigo_ibge, sigla, nome) values (33,'RJ', 'Rio de Janeiro');
insert into estado (codigo_ibge, sigla, nome) values (35,'SP', 'Sao Paulo');
insert into estado (codigo_ibge, sigla, nome) values (41,'PR', 'Parana');
insert into estado (codigo_ibge, sigla, nome) values (42,'SC', 'Santa Catarina');
insert into estado (codigo_ibge, sigla, nome) values (43,'RS', 'Rio Grande do Sul');
insert into estado (codigo_ibge, sigla, nome) values (50,'MS', 'Mato Grosso do Sul');
insert into estado (codigo_ibge, sigla, nome) values (51,'MT', 'Mato Grosso');
insert into estado (codigo_ibge, sigla, nome) values (52,'GO', 'Goias');
insert into estado (codigo_ibge, sigla, nome) values (53,'DF', 'Distrito Federal');
